
/* 0: 11*/
const char content_11[] = 
"Whooooaaaaa.......\n"
"<Arthur> Go Sir Galahad.\n"
"<bridge keeper> Stop, what is your name?\n"
"1. My name is Sir Lancelot of Camelot.\n"
"2. My name is Sir Robin.\n"
"3. Sir Galahad of Camelot.\n"
"4. It is Arthur, king of the Britons.";
/* 1: 21*/
const char content_21[] = 
"<bridge keeper> I don't know that. Whooooaaaaa.......\n"
"\n"
"You win! ";
/* 2: 7*/
const char content_7[] = 
"<Arthur> Good luck, brave Sir Lancelot. God be with you.";
/* 3: 17*/
const char content_17[] = 
"<bridge keeper> What is your favorite color?\n"
"1. Blue. No, yel...\n"
"2. Blue\n"
"3. I do not have one";
/* 4: 2*/
const char content_2[] = 
"<Arthur> Brave Sir Robin, you go.\n"
"1. I won't go.\n"
"2. I've got a great idea. Why doesn't Lancelot go?\n"
"3. That's easy!";
/* 5: 22*/
const char content_22[] = 
"Whooooaaaaa.......\n"
"\n"
"You lost Sir Lancelot and the game.";
/* 6: 1*/
const char content_1[] = 
"The knights of the round table are at the Bridge of Death. Thereis the old man from scene 24. He's the keeper of the Bridge of Death. He asks each traveler five questions. Er, three questions.He who answers the five que... three questions may cross in safety. Your quest is to get the knights to the other side. If you get a question wrong, then you are cast into the Gorge of EternalPeril.";
/* 7: 18*/
const char content_18[] = 
"<bridge keeper> What is the capital of Assyria?\n"
"3. I don't know that!";
/* 8: 23*/
const char content_23[] = 
"Whooooaaaaa.......\n"
"\n"
"You lost Arthur and the game.";
/* 9: 16*/
const char content_16[] = 
"<bridge keeper> What is your quest?\n"
"1. To seek the Holy Grail.\n"
"2. To seek the Holy Grail. ";
/* 10: 13*/
const char content_13[] = 
"<bridge keeper> What is your quest?\n"
"1. To seek the Holy Grail.\n"
"2. Impersonate Clark Gable";
/* 11: 25*/
const char content_25[] = 
"<bridge keeper> Stop! Who approacheth the Bridge of Death must answer me these questions three... ere the other side he see.\n"
"1. Ask me the questions, bridge keeper. I am not afraid.\n"
"2. Stand aside!";
/* 12: 6*/
const char content_6[] = 
"<Arthur> Three questions as best you can and we shall watch and pray. Good luck, brave Sir Lancelot. God be with you.";
/* 13: 3*/
const char content_3[] = 
"<Lancelot> Let me go. I will take it single-handed. I shall make a feint to the northeast...\n"
"<Arthur> No. Hang on. Just answer the five questions...\n"
"1. Three questions.\n"
"2. I understand.";
/* 14: 9*/
const char content_9[] = 
"<bridge keeper> What is your name?\n"
"1. My name is Sir Lancelot of Camelot.\n"
"2. My name is Sir Robin.\n"
"3. Sir Galahad of Camelot.\n"
"4. It is Arthur, king of the Britons.";
/* 15: 12*/
const char content_12[] = 
"Whooooaaaaa.......\n"
"<Arthur> Well...\n"
"<bridge keeper> Stop! What is your name?\n"
"1. My name is Sir Lancelot of Camelot.\n"
"2. My name is Sir Robin.\n"
"3. Sir Galahad of Camelot.\n"
"4. It is Arthur, king of the Britons.";
/* 16: 20*/
const char content_20[] = 
"<bridge keeper> What is your favorite color?\n"
"1. Blue. No, yel...\n"
"2. Blue\n"
"3. I don't know that!";
/* 17: 14*/
const char content_14[] = 
"<bridge keeper> What is your quest?\n"
"1. To seek the Holy Grail.\n"
"2. Stay alive?";
/* 18: 15*/
const char content_15[] = 
"<bridge keeper> What is your quest?\n"
"1. To seek the Holy Grail.\n"
"2. Get as much peril as I can...";
/* 19: 8*/
const char content_8[] = 
"<bridge keeper> Stop! Who would cross the Bridge of Death must answer me these questions three... ere the other side he see.\n"
"1. Ask me the questions, bridge keeper. I am not afraid.\n"
"2. Stand aside!";
/* 20: 4*/
const char content_4[] = 
"<Lancelot> Yes, let me go. I will take it single-handed. I shall make a feint to the northeast...\n"
"<Arthur> No. Hang on. Just answer the five questions...\n"
"1. Three questions.\n"
"2. I understand.";
/* 21: 24*/
const char content_24[] = 
"<bridge keeper> Right. Off you go.\n"
"<Lancelot> Oh, thank you very much.\n"
"<Sir Robin> That's easy!";
/* 22: 19*/
const char content_19[] = 
"<bridge keeper> What is the airspeed velocity of an unladen swallow?\n"
"1. What do you mean, an African or a European swallow?\n"
"2. I don't know that.";
/* 23: 10*/
const char content_10[] = 
"<bridge keeper> What is your name?\n"
"1. My name is Sir Lancelot of Camelot.\n"
"2. My name is Sir Robin.\n"
"3. Sir Galahad of Camelot.\n"
"4. It is Arthur, king of the Britons.";
/* 24: 5*/
const char content_5[] = 
"<Lancelot> No, let me go. I will take it single-handed. I shall make a feint to the northeast...\n"
"<Arthur> No. Hang on. Just answer the five questions...\n"
"1. Three questions.\n"
"2. I understand.";


const unsigned short cont_pointer[26];

const unsigned char links[52] = 
{
15, 15, 18, 15, /* 0: 11*/
6, /* 1: 21*/
19, /* 2: 7*/
5, 21, 5, /* 3: 17*/
13, 20, 24, /* 4: 2*/
6, /* 5: 22*/
4, /* 6: 1*/
0, /* 7: 18*/
6, /* 8: 23*/
22, 22, /* 9: 16*/
3, 5, /* 10: 13*/
23, 0, /* 11: 25*/
19, /* 12: 6*/
12, 2, /* 13: 3*/
10, 5, 5, 5, /* 14: 9*/
8, 8, 8, 9, /* 15: 12*/
15, 15, 15, /* 16: 20*/
7, /* 17: 14*/
16, 15, /* 18: 15*/
14, 5, /* 19: 8*/
12, 2, /* 20: 4*/
11, /* 21: 24*/
1, 8, /* 22: 19*/
0, 17, 0, 0, /* 23: 10*/
12, 2, /* 24: 5*/
};

const unsigned short link_pointer[26] = 
{
0, 4, 5, 6, 9, 12, 13, 14, 15, 16, 
18, 20, 22, 23, 25, 29, 33, 36, 37, 39, 
41, 43, 44, 46, 50, 52
};

const unsigned char poi_def = 6;

void init(void)
{
  cont_pointer[0] = content_11;
  cont_pointer[1] = content_21;
  cont_pointer[2] = content_7;
  cont_pointer[3] = content_17;
  cont_pointer[4] = content_2;
  cont_pointer[5] = content_22;
  cont_pointer[6] = content_1;
  cont_pointer[7] = content_18;
  cont_pointer[8] = content_23;
  cont_pointer[9] = content_16;
  cont_pointer[10] = content_13;
  cont_pointer[11] = content_25;
  cont_pointer[12] = content_6;
  cont_pointer[13] = content_3;
  cont_pointer[14] = content_9;
  cont_pointer[15] = content_12;
  cont_pointer[16] = content_20;
  cont_pointer[17] = content_14;
  cont_pointer[18] = content_15;
  cont_pointer[19] = content_8;
  cont_pointer[20] = content_4;
  cont_pointer[21] = content_24;
  cont_pointer[22] = content_19;
  cont_pointer[23] = content_10;
  cont_pointer[24] = content_5;
 
}

